"""Prototipo di compilazione quantistica assistita da un LLM."""

from .adapters.context import EvidenceRegistryDataError
from .controller import PrototypeController
from .factory import build_default_service
from .errors import RequestValidationError
from .models import (
    ApprovedCompilation,
    CircuitInput,
    CompatibilityReport,
    CompatibilityView,
    CompilationArtifact,
    DeviceExclusionDiagnostic,
    DeviceExclusionReason,
    DeviceQubitRange,
    EvidenceRecord,
    EvidenceReference,
    EvidenceRegistry,
    EvidenceSourceType,
    HistoricalClaim,
    HistoricalClaimType,
    HistoricalConfiguration,
    HistoricalEvidence,
    HardwareCatalogSnapshot,
    HardwareConstraints,
    HardwareMaskResult,
    NormalizedRequest,
    PreparedRequestContext,
    Recommendation,
    RecommendationResult,
    RenderedExplanation,
    ScientificCaveat,
    SupportedClaim,
    SupportedClaimType,
    ClaimParameters,
    UiSubmission,
    UserRequest,
    ValidationIssue,
    ValidationReport,
)
from .services import (
    ConfirmationRequiredError,
    LlmValidationExhaustedError,
    NoCompatibleHardwareError,
    NoEligibleDeviceError,
    PrototypeService,
    UnvalidatedRecommendationError,
)

__all__ = [
    "ApprovedCompilation",
    "CircuitInput",
    "CompatibilityReport",
    "CompatibilityView",
    "CompilationArtifact",
    "ConfirmationRequiredError",
    "DeviceExclusionDiagnostic",
    "DeviceExclusionReason",
    "DeviceQubitRange",
    "EvidenceRecord",
    "EvidenceReference",
    "EvidenceRegistryDataError",
    "EvidenceRegistry",
    "EvidenceSourceType",
    "HistoricalClaim",
    "HistoricalClaimType",
    "HistoricalConfiguration",
    "HistoricalEvidence",
    "HardwareCatalogSnapshot",
    "HardwareConstraints",
    "HardwareMaskResult",
    "LlmValidationExhaustedError",
    "NoCompatibleHardwareError",
    "NoEligibleDeviceError",
    "NormalizedRequest",
    "PreparedRequestContext",
    "PrototypeController",
    "PrototypeService",
    "Recommendation",
    "RecommendationResult",
    "RenderedExplanation",
    "ScientificCaveat",
    "SupportedClaim",
    "SupportedClaimType",
    "ClaimParameters",
    "RequestValidationError",
    "UiSubmission",
    "UnvalidatedRecommendationError",
    "UserRequest",
    "ValidationIssue",
    "ValidationReport",
    "build_default_service",
]
